name: famous_quote_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.1.1
  flutter_native_timezone: ^2.0.0
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true
