name: famous_quote_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.9.2
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.2
  intl: any
  flutter_slidable: ^3.0.0
  flutter_local_notifications: ^15.1.1

  flutter_app_badger: ^1.5.0
  sqflite: ^2.3.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter:
  assets:
   - assets/images/
  
  uses-material-design: true
